name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set Electron Platform
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "ELECTRON_PLATFORM=linux" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "ELECTRON_PLATFORM=win32" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "ELECTRON_PLATFORM=darwin" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set Electron Arch
        run: |
          echo "ELECTRON_ARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build Electron App
        run: npm run make -- --platform=$ELECTRON_PLATFORM --arch=$ELECTRON_ARCH

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: out/make/